---
abstract: 'SAML authentication provider for Catalyst'
author:
  - 'Andy Brezinsky <andy@mbrez.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Authentication-Credential-SAML2
version: 0.001
